name: reviewdog
on:
  pull_request:
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reviewdog by golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: go.mod
          reporter: github-pr-check
          level: warning
