name: test
on:
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Run tests
        run: go test ./...
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Run tests
        run: go test ./...
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Run tests
        run: go test ./...
